//@ sourceMappingURL=express-django.map
// Generated by CoffeeScript 1.6.1
(function() {
  var createApp, express;

  createApp = void 0;

  express = void 0;

  express = require("express");

  createApp = function() {
    var project;
    project = void 0;
    project = express();
    project.install = function(app, url) {
      if (app instanceof String) {
        app = require(app);
      }
      return app.install({
        app: project,
        url: url
      });
    };
    return project;
  };

  module.exports = {
    Installer: require("./installer"),
    View: require("./view"),
    express: createApp
  };

}).call(this);
