//@ sourceMappingURL=express-django.map
// Generated by CoffeeScript 1.6.1
(function() {
  var add_routing, createApp, express, install;

  createApp = void 0;

  express = void 0;

  express = require("express");

  install = function(app, url) {
    if (app instanceof String) {
      app = require(app);
    }
    return app.install({
      app: project,
      url: url
    });
  };

  add_routing = function(app) {};

  createApp = function() {
    var project;
    project = void 0;
    project = express();
    project.install = install;
    return project;
  };

  module.exports = {
    Installer: require("./installer"),
    View: require("./view"),
    express: createApp
  };

}).call(this);
